#!/bin/bash
set -e

PGPASSWORD=${POSTGRES_PASSWORD} psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$ILMAKALU_DB" -h localhost <<-EOSQL
    CREATE EXTENSION postgis;
    CREATE EXTENSION dblink;
    CREATE EXTENSION postgres_fdw;
    CREATE SERVER $ILMAKALU_COMPUTE_SERVICE_NAME FOREIGN DATA WRAPPER postgres_fdw OPTIONS (dbname '$ILMAKALU_REMOTE_DB', host 'database');
    CREATE USER MAPPING FOR "$ILMAKALU_USER" SERVER $ILMAKALU_COMPUTE_SERVICE_NAME OPTIONS (user '$ILMAKALU_REMOTE_USER', password '$ILMAKALU_REMOTE_USER_PW');
    GRANT USAGE ON FOREIGN SERVER $ILMAKALU_COMPUTE_SERVICE_NAME TO $ILMAKALU_USER;
EOSQL