CREATE USER emissiontest WITH PASSWORD '123';
CREATE USER internal WITH PASSWORD '123';
CREATE USER schemacreator WITH PASSWORD '123';
CREATE USER tablecreator WITH PASSWORD '123';
CREATE USER cloudsqladmin WITH PASSWORD '123';
CREATE USER cloudsqlsuperuser WITH SUPERUSER PASSWORD '123';
GRANT schemacreator TO ilmakalu;
CREATE GROUP organisationname;
GRANT organisationname TO ilmakalu;
GRANT tablecreator TO ilmakalu;
