from database import Base, create_schema
from sqlalchemy.orm import Mapped, mapped_column

schema = 'grid_globals'
create_schema(schema)

class buildings(Base):
    __tablename__ = "buildings"
    __table_args__ = { 'schema': schema }
    xyind: Mapped[int] = mapped_column(primary_key=True)
    rakv: Mapped[int] = mapped_column(primary_key=True)
    energiam: Mapped[str] = mapped_column(primary_key=True)
    rakyht_lkm: Mapped[int] = mapped_column()
    teoll_lkm: Mapped[int] = mapped_column()
    varast_lkm: Mapped[int] = mapped_column()
    rakyht_ala: Mapped[int] = mapped_column()
    asuin_ala: Mapped[int] = mapped_column()
    erpien_ala: Mapped[int] = mapped_column()
    rivita_ala: Mapped[int] = mapped_column()
    askert_ala: Mapped[int] = mapped_column()
    liike_ala: Mapped[int] = mapped_column()
    myymal_ala: Mapped[int] = mapped_column()
    myymal_pien_ala: Mapped[int] = mapped_column()
    myymal_super_ala: Mapped[int] = mapped_column()
    myymal_hyper_ala: Mapped[int] = mapped_column()
    myymal_muu_ala: Mapped[int] = mapped_column()
    majoit_ala: Mapped[int] = mapped_column()
    asla_ala: Mapped[int] = mapped_column()
    ravint_ala: Mapped[int] = mapped_column()
    tsto_ala: Mapped[int] = mapped_column()
    liiken_ala: Mapped[int] = mapped_column()
    hoito_ala: Mapped[int] = mapped_column()
    kokoon_ala: Mapped[int] = mapped_column()
    opetus_ala: Mapped[int] = mapped_column()
    teoll_ala: Mapped[int] = mapped_column()
    teoll_elint_ala: Mapped[int] = mapped_column()
    teoll_tekst_ala: Mapped[int] = mapped_column()
    teoll_puu_ala: Mapped[int] = mapped_column()
    teoll_paper_ala: Mapped[int] = mapped_column()
    teoll_miner_ala: Mapped[int] = mapped_column()
    teoll_kemia_ala: Mapped[int] = mapped_column()
    teoll_kone_ala: Mapped[int] = mapped_column()
    teoll_mjalos_ala: Mapped[int] = mapped_column()
    teoll_metal_ala: Mapped[int] = mapped_column()
    teoll_vesi_ala: Mapped[int] = mapped_column()
    teoll_energ_ala: Mapped[int] = mapped_column()
    teoll_yhdysk_ala: Mapped[int] = mapped_column()
    teoll_kaivos_ala: Mapped[int] = mapped_column()
    teoll_muu_ala: Mapped[int] = mapped_column()
    varast_ala: Mapped[int] = mapped_column()
    muut_ala: Mapped[int] = mapped_column()

class clc(Base):
    __tablename__ = "clc"
    __table_args__ = { 'schema': schema }
    vuosi: Mapped[int] = mapped_column()
    kunta: Mapped[str] = mapped_column()
    maa_ha: Mapped[float] = mapped_column()
    vesi_ha: Mapped[float] = mapped_column()
    clc1111: Mapped[float] = mapped_column()
    clc1121: Mapped[float] = mapped_column()
    clc1211: Mapped[float] = mapped_column()
    clc1212: Mapped[float] = mapped_column()
    clc1221: Mapped[float] = mapped_column()
    clc1231: Mapped[float] = mapped_column()
    clc1241: Mapped[float] = mapped_column()
    clc1311: Mapped[float] = mapped_column()
    clc1312: Mapped[float] = mapped_column()
    clc1321: Mapped[float] = mapped_column()
    clc1331: Mapped[float] = mapped_column()
    clc1411: Mapped[float] = mapped_column()
    clc1421: Mapped[float] = mapped_column()
    clc1422: Mapped[float] = mapped_column()
    clc1423: Mapped[float] = mapped_column()
    clc1424: Mapped[float] = mapped_column()
    clc2111: Mapped[float] = mapped_column()
    clc2221: Mapped[float] = mapped_column()
    clc2311: Mapped[float] = mapped_column()
    clc2312: Mapped[float] = mapped_column()
    clc2431: Mapped[float] = mapped_column()
    clc2441: Mapped[float] = mapped_column()
    clc3111: Mapped[float] = mapped_column()
    clc3112: Mapped[float] = mapped_column()
    clc3121: Mapped[float] = mapped_column()
    clc3122: Mapped[float] = mapped_column()
    clc3123: Mapped[float] = mapped_column()
    clc3131: Mapped[float] = mapped_column()
    clc3132: Mapped[float] = mapped_column()
    clc3133: Mapped[float] = mapped_column()
    clc3211: Mapped[float] = mapped_column()
    clc3221: Mapped[float] = mapped_column()
    clc3241: Mapped[float] = mapped_column()
    clc3242: Mapped[float] = mapped_column()
    clc3243: Mapped[float] = mapped_column()
    clc3244: Mapped[float] = mapped_column()
    clc3246: Mapped[float] = mapped_column()
    clc3311: Mapped[float] = mapped_column()
    clc3321: Mapped[float] = mapped_column()
    clc3331: Mapped[float] = mapped_column()
    clc4111: Mapped[float] = mapped_column()
    clc4112: Mapped[float] = mapped_column()
    clc4121: Mapped[float] = mapped_column()
    clc4122: Mapped[float] = mapped_column()
    clc4211: Mapped[float] = mapped_column()
    clc4212: Mapped[float] = mapped_column()
    clc5111: Mapped[float] = mapped_column()
    clc5121: Mapped[float] = mapped_column()
    clc5231: Mapped[float] = mapped_column()
    xyind: Mapped[int] = mapped_column(primary_key=True)

class employ(Base):
    __tablename__ = "employ"
    __table_args__ = { 'schema': schema }
    vuosi: Mapped[int] = mapped_column(primary_key=True)
    kunta: Mapped[str] = mapped_column()
    tp_yht: Mapped[int] = mapped_column()
    xyind: Mapped[int] = mapped_column(primary_key=True)

class pop(Base):
    __tablename__ = "pop"
    __table_args__ = { 'schema': schema }
    vuosi: Mapped[int] = mapped_column(primary_key=True)
    kunta: Mapped[str] = mapped_column()
    xyind: Mapped[int] = mapped_column(primary_key=True)
    v_yht: Mapped[int] = mapped_column()
    v_0_6: Mapped[int] = mapped_column()
    v_7_14: Mapped[int] = mapped_column()
    v_15_17: Mapped[int] = mapped_column()
    v_18_29: Mapped[int] = mapped_column()
    v_30_49: Mapped[int] = mapped_column()
    v_50_64: Mapped[int] = mapped_column()
    v_65_74: Mapped[int] = mapped_column()
    v_75: Mapped[int] = mapped_column()