version: "3.8"

# TODO:
# map volumes to physical locations on disk
volumes:
  ilmakalu-data:
    external: false
    
services:
  ilmakalu_api:
    container_name: ilmakalu_api
    image: fastapi:1.0.0
    build:
      context: ./../backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    restart: always
    environment:
      - DATABASE_URL=postgresql://docker:docker@ilmakalu_user:5432/ilmakalu_data
    depends_on:
      - ilmakalu_user
  ilmakalu_user:
    container_name: ilmakalu_user
    image: kartoza/postgis:13.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ilmakalu_data
#      POSTGRES_MULTIPLE_EXTENSIONS: postgis,"uuid-ossp"
      DEFAULT_CTYPE: 'fi_FI.UTF8'
      DEFAULT_COLLATION: 'fi_FI.UTF8'
      TZ: Europe/Helsinki
      PASSWORD_AUTHENTICATION: "md5"
    volumes:
      - ilmakalu-data:/var/lib/postgresql # Add :cached if needed. This is for Linux env and now dev is done on windows. 
    ports:
      - "65432:5432"
    restart: on-failure
    healthcheck:
     test: "exit 0"
    shm_size: 1g
