#!/bin/bash
set -e

PGPASSWORD=${POSTGRES_PASSWORD} psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -h localhost <<-EOSQL
    CREATE DATABASE ${ILMAKALU_DB};
    CREATE USER ${ILMAKALU_USER} WITH PASSWORD '${ILMAKALU_USER_PW}';
    GRANT ALL PRIVILEGES ON DATABASE ${ILMAKALU_DB} TO ${ILMAKALU_USER};
    ALTER DATABASE ${ILMAKALU_DB} OWNER TO ${ILMAKALU_DB};
EOSQL