from app import db, createSchema

schema = 'grid_globals'
createSchema(schema)

class buildings(db.Model):
    __table_args__ = { 'schema': schema }
    xyind = db.Column(db.Integer, primary_key=True)
    rakv = db.Column(db.Integer, primary_key=True)
    energiam = db.Column(db.Text, primary_key=True)
    rakyht_lkm = db.Column(db.Integer)
    teoll_lkm = db.Column(db.Integer)
    varast_lkm = db.Column(db.Integer)
    rakyht_ala = db.Column(db.Integer)
    asuin_ala = db.Column(db.Integer)
    erpien_ala = db.Column(db.Integer)
    rivita_ala = db.Column(db.Integer)
    askert_ala = db.Column(db.Integer)
    liike_ala = db.Column(db.Integer)
    myymal_ala = db.Column(db.Integer)
    myymal_pien_ala = db.Column(db.Integer)
    myymal_super_ala = db.Column(db.Integer)
    myymal_hyper_ala = db.Column(db.Integer)
    myymal_muu_ala = db.Column(db.Integer)
    majoit_ala = db.Column(db.Integer)
    asla_ala = db.Column(db.Integer)
    ravint_ala = db.Column(db.Integer)
    tsto_ala = db.Column(db.Integer)
    liiken_ala = db.Column(db.Integer)
    hoito_ala = db.Column(db.Integer)
    kokoon_ala = db.Column(db.Integer)
    opetus_ala = db.Column(db.Integer)
    teoll_ala = db.Column(db.Integer)
    teoll_elint_ala = db.Column(db.Integer)
    teoll_tekst_ala = db.Column(db.Integer)
    teoll_puu_ala = db.Column(db.Integer)
    teoll_paper_ala = db.Column(db.Integer)
    teoll_miner_ala = db.Column(db.Integer)
    teoll_kemia_ala = db.Column(db.Integer)
    teoll_kone_ala = db.Column(db.Integer)
    teoll_mjalos_ala = db.Column(db.Integer)
    teoll_metal_ala = db.Column(db.Integer)
    teoll_vesi_ala = db.Column(db.Integer)
    teoll_energ_ala = db.Column(db.Integer)
    teoll_yhdysk_ala = db.Column(db.Integer)
    teoll_kaivos_ala = db.Column(db.Integer)
    teoll_muu_ala = db.Column(db.Integer)
    varast_ala = db.Column(db.Integer)
    muut_ala = db.Column(db.Integer)

class clc(db.Model):
    __table_args__ = { 'schema': schema }
    vuosi = db.Column(db.Integer)
    kunta = db.Column(db.Text)
    maa_ha = db.Column(db.Float)
    vesi_ha = db.Column(db.Float)
    clc1111 = db.Column(db.Float)
    clc1121 = db.Column(db.Float)
    clc1211 = db.Column(db.Float)
    clc1212 = db.Column(db.Float)
    clc1221 = db.Column(db.Float)
    clc1231 = db.Column(db.Float)
    clc1241 = db.Column(db.Float)
    clc1311 = db.Column(db.Float)
    clc1312 = db.Column(db.Float)
    clc1321 = db.Column(db.Float)
    clc1331 = db.Column(db.Float)
    clc1411 = db.Column(db.Float)
    clc1421 = db.Column(db.Float)
    clc1422 = db.Column(db.Float)
    clc1423 = db.Column(db.Float)
    clc1424 = db.Column(db.Float)
    clc2111 = db.Column(db.Float)
    clc2221 = db.Column(db.Float)
    clc2311 = db.Column(db.Float)
    clc2312 = db.Column(db.Float)
    clc2431 = db.Column(db.Float)
    clc2441 = db.Column(db.Float)
    clc3111 = db.Column(db.Float)
    clc3112 = db.Column(db.Float)
    clc3121 = db.Column(db.Float)
    clc3122 = db.Column(db.Float)
    clc3123 = db.Column(db.Float)
    clc3131 = db.Column(db.Float)
    clc3132 = db.Column(db.Float)
    clc3133 = db.Column(db.Float)
    clc3211 = db.Column(db.Float)
    clc3221 = db.Column(db.Float)
    clc3241 = db.Column(db.Float)
    clc3242 = db.Column(db.Float)
    clc3243 = db.Column(db.Float)
    clc3244 = db.Column(db.Float)
    clc3246 = db.Column(db.Float)
    clc3311 = db.Column(db.Float)
    clc3321 = db.Column(db.Float)
    clc3331 = db.Column(db.Float)
    clc4111 = db.Column(db.Float)
    clc4112 = db.Column(db.Float)
    clc4121 = db.Column(db.Float)
    clc4122 = db.Column(db.Float)
    clc4211 = db.Column(db.Float)
    clc4212 = db.Column(db.Float)
    clc5111 = db.Column(db.Float)
    clc5121 = db.Column(db.Float)
    clc5231 = db.Column(db.Float)
    xyind = db.Column(db.Integer, primary_key=True)

class employ(db.Model):
    __table_args__ = { 'schema': schema }
    vuosi = db.Column(db.Integer, primary_key=True)
    kunta = db.Column(db.Text)
    tp_yht = db.Column(db.Integer)
    xyind = db.Column(db.Integer, primary_key=True)

class pop(db.Model):
    __table_args__ = { 'schema': schema }
    vuosi = db.Column(db.Integer, primary_key=True)
    kunta = db.Column(db.Text)
    xyind = db.Column(db.Integer, primary_key=True)
    v_yht = db.Column(db.Integer)
    v_0_6 = db.Column(db.Integer)
    v_7_14 = db.Column(db.Integer)
    v_15_17 = db.Column(db.Integer)
    v_18_29 = db.Column(db.Integer)
    v_30_49 = db.Column(db.Integer)
    v_50_64 = db.Column(db.Integer)
    v_65_74 = db.Column(db.Integer)
    v_75 = db.Column(db.Integer)
