name: Docker Image CI

on:
  push:
    branches: [ "tampere-plain" ]
  workflow_dispatch:
#  pull_request:
#    branches: [ "main" ]

env:
  NODE_VERSION: 18
  IMAGE_NAME: ${{ secrets.REGISTRY_ADDRESS }}/ilmakalu/tampere

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download database dump
      working-directory: services/tampere/dump
      run: pg_dump "host=${{ secrets.ILMAKALU_UBIHUB_HOST }} user=${{ secrets.ILMAKALU_UBIHUB_USER }} password=${{ secrets.ILMAKALU_UBIHUB_PASSWORD }} dbname=${{ secrets.ILMAKALU_UBIHUB_DATABASE }}" > emissiontest_stripped.sql
    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_ADDRESS }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD2 }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: services/tampere
        push: true
        tags: ${{ env.IMAGE_NAME }}